// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package image

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/hashicorp/packer-plugin-sdk/template/config"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName       *string                `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType     *string                `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion     *string                `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug           *bool                  `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce           *bool                  `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError         *string                `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars        map[string]string      `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars   []string               `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	ClientID              *string                `mapstructure:"client_id" required:"true" cty:"client_id" hcl:"client_id"`
	ClientSecret          *string                `mapstructure:"client_secret" required:"true" cty:"client_secret" hcl:"client_secret"`
	SpaceID               *string                `mapstructure:"space_id" required:"true" cty:"space_id" hcl:"space_id"`
	Region                *string                `mapstructure:"region" required:"false" cty:"region" hcl:"region"`
	InsecureSkipTLSVerify *bool                  `mapstructure:"insecure_skip_tls_verify" required:"false" cty:"insecure_skip_tls_verify" hcl:"insecure_skip_tls_verify"`
	Filters               map[string]string      `cty:"filters" hcl:"filters"`
	Filter                []config.FlatNameValue `cty:"filter" hcl:"filter"`
	Owners                []string               `mapstructure:"owners" required:"false" cty:"owners" hcl:"owners"`
	MostRecent            *bool                  `mapstructure:"most_recent" required:"false" cty:"most_recent" hcl:"most_recent"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"client_id":                  &hcldec.AttrSpec{Name: "client_id", Type: cty.String, Required: false},
		"client_secret":              &hcldec.AttrSpec{Name: "client_secret", Type: cty.String, Required: false},
		"space_id":                   &hcldec.AttrSpec{Name: "space_id", Type: cty.String, Required: false},
		"region":                     &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"insecure_skip_tls_verify":   &hcldec.AttrSpec{Name: "insecure_skip_tls_verify", Type: cty.Bool, Required: false},
		"filters":                    &hcldec.AttrSpec{Name: "filters", Type: cty.Map(cty.String), Required: false},
		"filter":                     &hcldec.BlockListSpec{TypeName: "filter", Nested: hcldec.ObjectSpec((*config.FlatNameValue)(nil).HCL2Spec())},
		"owners":                     &hcldec.AttrSpec{Name: "owners", Type: cty.List(cty.String), Required: false},
		"most_recent":                &hcldec.AttrSpec{Name: "most_recent", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	ID             *string           `mapstructure:"id" cty:"id" hcl:"id"`
	Name           *string           `mapstructure:"name" cty:"name" hcl:"name"`
	Description    *string           `mapstructure:"description" cty:"description" hcl:"description"`
	CreationDate   *string           `mapstructure:"creation_date" cty:"creation_date" hcl:"creation_date"`
	State          *string           `mapstructure:"state" cty:"state" hcl:"state"`
	Architecture   *string           `mapstructure:"architecture" cty:"architecture" hcl:"architecture"`
	RootDeviceName *string           `mapstructure:"root_device_name" cty:"root_device_name" hcl:"root_device_name"`
	RootDeviceType *string           `mapstructure:"root_device_type" cty:"root_device_type" hcl:"root_device_type"`
	Tags           map[string]string `mapstructure:"tags" cty:"tags" hcl:"tags"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":               &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"name":             &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"description":      &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"creation_date":    &hcldec.AttrSpec{Name: "creation_date", Type: cty.String, Required: false},
		"state":            &hcldec.AttrSpec{Name: "state", Type: cty.String, Required: false},
		"architecture":     &hcldec.AttrSpec{Name: "architecture", Type: cty.String, Required: false},
		"root_device_name": &hcldec.AttrSpec{Name: "root_device_name", Type: cty.String, Required: false},
		"root_device_type": &hcldec.AttrSpec{Name: "root_device_type", Type: cty.String, Required: false},
		"tags":             &hcldec.AttrSpec{Name: "tags", Type: cty.Map(cty.String), Required: false},
	}
	return s
}
